### ISSUE TITLE
[Mobile] No images on card pages

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#33]
Individual card pages don't show any images.

Phone: [TECNO-N9](http://www.orange.mg/particulier/2/particuliers/1/19/tecno-n9-1493.html)

![22](https://user-images.githubusercontent.com/7605827/30777377-d7b088ee-a0c1-11e7-8738-cf694f0d1ab1.jpg)

**Comment by Alsciende** [comment]
I can't reproduce this issue. Can you force-refresh and retry?

**Comment by mplain** [comment]
It shows the image now, thanks!
