### ISSUE TITLE
[Rulings] Add rulings to the pop-up window and to search results

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#34]
Currently the rulings are only visible on the individual card pages, and not many people ever get there.

If you could please make rulings aslo show up in the pop-up window when clicking a card title.

Also, if Search gives out only one result, it shows it the same way as an individual card page, with card art and data, but without rulings. Could you please make rulings show up in that case as well? Example: https://fiveringsdb.com/cards/search?q=Calling%20in%20Favors

**Comment by Alsciende** [comment]
No rulings on the popup, but yes to second request.

**Comment by mplain** [comment]
When at an individual card page, links from the Rulings section lead to https://fiveringsdb.com/card/ and function correctly.

When at a Search result page showing only one card, links from the Rulings section lead to https://fiveringsdb.com/cardS/ and lead to Page Not Found.

![1](https://user-images.githubusercontent.com/7605827/30786538-3ad2c248-a180-11e7-8b58-856eafa359ae.png)
![2](https://user-images.githubusercontent.com/7605827/30786540-3cc7e02e-a180-11e7-9cd7-61ab605aa7db.png)

**Comment by Alsciende** [comment]
Don't use this way of linking. Use an absolute url.

**Comment by Alsciende** [comment]
Also, don't piggy-back on existing issues. Create new ones for new problems, other I can't track them correctly.
