### ISSUE TITLE
[Sugestion] Add on-hover explanation of keywords

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#35]
Similar to how it's done on thronesdb. That would also help with cards that grant keywords to other cards.

![1](https://user-images.githubusercontent.com/7605827/30777439-26dd0df6-a0c3-11e7-816e-700d63f105f4.png)

**Comment by Alsciende** [comment]
No, I'm not interested in implementing this feature. There's a nice indexed Rules Reference if anyone has a doubt.
