### ISSUE TITLE
[Suggestion] Show traits in bold italics right above the card text

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#37]
Same way it is on thronesdb. After all it is a part of the printed text box.

![1](https://user-images.githubusercontent.com/7605827/30777469-bfa92308-a0c3-11e7-9ed3-d80569404778.png)

**Comment by Alsciende** [comment]
Already done.

**Comment by mplain** [comment]
Just to clarify, I'm asking for Traits to be on a separate line from Clan + Cardtype, below the cost and right above the card text. My reasoning is that traits are a part of the text box, not subtypes like in MTG.

**Comment by Alsciende** [comment]
No, I'm ok with how it is at the moment.
