### ISSUE TITLE
[Suggestion] Add exclusive-select option to the deckbuilder

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#38]
Functionality that I miss dearly fro thronesdb, please please add this!

![1](https://user-images.githubusercontent.com/7605827/30777485-06620b48-a0c4-11e7-8de5-7aa9bfeaf341.png)

**Comment by Alsciende** [comment]
closed by https://github.com/Alsciende/fiveringsdb-ui/commit/914c7cc81e7f7b3d390870471495d1b47785d8a8

**Comment by mplain** [comment]
Thanks for adding this feature. Although, it doesn't work on mobile - can't hold shift there. Any chance you could make a checkbox in user settings or something? Thanks!
