### ISSUE TITLE
[Suggestion] Remove Province and Role deck filters

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#39]
I suggest removing the Province and Role deck filters, they're redundant with the same type filters. It's not very convenient to have to click two different buttons, somewhat confusing.

![1](https://user-images.githubusercontent.com/7605827/30777510-7a4ef19c-a0c4-11e7-9926-6796569b26de.png)

**Comment by Alsciende** [comment]
A simple solution is to use either the "deck" filter, or the "type" filter, but not both.

Leave all the types checked, and use the decks. Or leave all the decks checked, and use the types.

Due to how the types and decks interact, I can't change that right now.
