### ISSUE TITLE
[Bug] Sorting by type doesn't work

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#41]
I remember these buttons used to work before, but now they don't (I click them but nothing happens).

![1](https://user-images.githubusercontent.com/7605827/30777548-5c283c86-a0c5-11e7-98aa-ad197360194e.png)

**Comment by Alsciende** [comment]
Already fixed.

**Comment by mplain** [comment]
Still does not work for me. I'm under Chrome, and all the other fixes you deplayed function by now.
