### ISSUE TITLE
[Rulings] Visual glitch

### ISSUE THREAD

**Issue by mplain** [Alsciende/fiveringsdb-api#45]
I get this a lot when editing rulings. Windows 10, Chrome.

![1](https://user-images.githubusercontent.com/7605827/31306193-70acce0e-ab53-11e7-8846-c9d41d4b9fac.png)
![2](https://user-images.githubusercontent.com/7605827/31306194-70c56374-ab53-11e7-9dd5-801b5d286dd3.png)

**Comment by Alsciende** [comment]
That's weird, but fixing the Windows 10 3D display engine is a bit above my competence :) There's nothing I can do.
