### ISSUE TITLE
[Comments] Published Decks

### ISSUE THREAD

**Issue by barrysheppard** [Alsciende/fiveringsdb-api#47]
On this published deck https://fiveringsdb.com/decks/6705208d-ac34-11e7-8e3c-8e1ccf16fca4/view I can sometimes see 1 comment
 
ayedubbleyoo
2 days ago
No Unassuming Yojimbo?

Other times I can see more but not the above. The total is listed at 4.

Something weird going on.

Similarly 
https://fiveringsdb.com/decks/81fda06f-abe2-11e7-8e3c-8e1ccf16fca4/view
listed as 12 comments but only 9 are there when I click into it.

**Comment by barrysheppard** [comment]
Weird, posting a response to the comment I could see let me see all the additional comments!

**Comment by Alsciende** [comment]
Fixed with 08464b682fb27ef06fbacaebe46df20acf01d2c3, thanks.
