### ISSUE TITLE
Rulings do not appear on card page until logout and back in.

### ISSUE THREAD

**Issue by inniscor** [Alsciende/fiveringsdb-api#49]
For at least two users rulings did not show up on the card page (ex. https://fiveringsdb.com/card/savvy-politician) and client errors appeared (did not save the contents).

After logging out and back in this issue was resolved for both of us.

**Comment by Alsciende** [comment]
I can't seem to reproduce the problem. Do you have another example?

**Comment by inniscor** [comment]
![image](https://user-images.githubusercontent.com/843023/31875747-45cb2c52-b784-11e7-844e-2748c4bc4f0b.png)

Here's a screenshot on my home computer. I haven't logged out and logged back in to reset. This seems like some sort of caching issue.

**Comment by Alsciende** [comment]
I'm assuming the issue is resolved.
