### ISSUE TITLE
Want to translate fiveringsdb

### ISSUE THREAD

**Issue by fatelesscn** [Alsciende/fiveringsdb-api#77]
I want to transalte this site with chinese language,the same to http://zh.swdestinydb.com/
How can i do it? Thank U!

**Comment by Alsciende** [comment]
There's no plan currently to translate the site in another language, sorry.

**Comment by fatelesscn** [comment]
Many chinese player want to use it.I hope you can help us, thank you.

**Comment by fatelesscn** [comment]
Many chinese player want to use it.I hope you can help us, thank you.
